"""
FixMyEnglish - Telegram Voice Chat Media Player

Uses:
- python-telegram-bot for bot commands/buttons
- Pyrogram user session for reading/downloading Telegram media
- PyTgCalls for Telegram voice/video chats

Required environment variables:
    API_ID
    API_HASH
    SESSION_STRING

The bot itself still uses BOT_TOKEN in bot.py.
"""

from __future__ import annotations

import asyncio
import inspect
import logging
import os
import random
import shutil
import tempfile
from collections import deque
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from pyrogram import Client

from telegram import (
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    Update,
)

from telegram.ext import (
    Application,
    CallbackQueryHandler,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

try:
    from pytgcalls import PyTgCalls
    from pytgcalls import filters as call_filters
    from pytgcalls.types import (
        AudioQuality,
        MediaStream,
        StreamEnded,
        VideoQuality,
    )
except Exception:
    PyTgCalls = None
    call_filters = None
    AudioQuality = None
    MediaStream = None
    StreamEnded = None
    VideoQuality = None


log = logging.getLogger("FixMyEnglish.media_play")


# ============================================================
# CONFIG
# ============================================================

API_ID_RAW = os.getenv("API_ID", "").strip()
API_HASH = os.getenv("API_HASH", "").strip()
SESSION_STRING = os.getenv("SESSION_STRING", "").strip()
OWNER_ID_RAW = os.getenv("OWNER_ID", "").strip()

DOWNLOAD_TIMEOUT = 120
MESSAGE_TIMEOUT = 30
PLAY_TIMEOUT = 60

MAX_QUEUE = 50

ADMIN_STATUSES = {
    "administrator",
    "creator",
    "owner",
}

TEMP_ROOT = Path(tempfile.gettempdir()) / "fixmyenglish_media"
TEMP_ROOT.mkdir(parents=True, exist_ok=True)


def _int_env(value: str, name: str) -> int:
    try:
        return int(value)
    except Exception as exc:
        raise RuntimeError(f"{name} must be a valid integer.") from exc


if API_ID_RAW:
    API_ID = _int_env(API_ID_RAW, "API_ID")
else:
    API_ID = 0


OWNER_ID: Optional[int] = None

if OWNER_ID_RAW:
    try:
        OWNER_ID = int(OWNER_ID_RAW)
    except ValueError:
        log.warning(
            "OWNER_ID is not a valid integer; owner override disabled."
        )


# ============================================================
# ENGINE GLOBALS
# ============================================================

USER_CLIENT: Optional[Client] = None
CALLS = None

# PTB Bot instance.
# Needed when the stream ends automatically and there is no Context
# object available to send the next "Now Playing" message.
BOT_INSTANCE = None

_ENGINE_LOCK = asyncio.Lock()
_ENGINE_READY = False
_EVENTS_REGISTERED = False


# ============================================================
# DATA MODELS
# ============================================================

@dataclass
class MediaItem:
    chat_id: int
    message_id: int
    title: str

    # audio / video
    kind: str

    requester_id: int

    # Topic where the user requested the media.
    thread_id: Optional[int] = None

    # Downloaded local file.
    temp_path: Optional[str] = None


@dataclass
class PlayerState:
    queue: deque
    current: Optional[MediaItem] = None

    paused: bool = False
    muted: bool = False

    volume: int = 100

    # off / one / all
    repeat: str = "off"

    starting: bool = False

    # Prevent a delayed stream_end event generated by manual
    # skip/stop from interfering with the next track.
    suppress_next_end: bool = False


PLAYERS: dict[int, PlayerState] = {}
CHAT_LOCKS: dict[int, asyncio.Lock] = {}


# ============================================================
# PLAYER STATE
# ============================================================

def _state(chat_id: int) -> PlayerState:
    if chat_id not in PLAYERS:
        PLAYERS[chat_id] = PlayerState(queue=deque())

    return PLAYERS[chat_id]


def _lock(chat_id: int) -> asyncio.Lock:
    if chat_id not in CHAT_LOCKS:
        CHAT_LOCKS[chat_id] = asyncio.Lock()

    return CHAT_LOCKS[chat_id]


# ============================================================
# MEDIA DETECTION
# ============================================================

def _media_from_message(message) -> tuple[str, str] | None:
    """
    Return:
        ("audio", title)
        ("video", title)

    for Telegram media that can be downloaded and processed.
    """

    if not message:
        return None

    audio = getattr(message, "audio", None)

    if audio:
        return (
            "audio",
            getattr(audio, "file_name", None) or "Audio",
        )

    video = getattr(message, "video", None)

    if video:
        return (
            "video",
            getattr(video, "file_name", None) or "Video",
        )

    voice = getattr(message, "voice", None)

    if voice:
        return (
            "audio",
            "Voice message",
        )

    document = getattr(message, "document", None)

    if document:
        mime = (
            getattr(document, "mime_type", None)
            or ""
        ).lower()

        if mime.startswith("audio/"):
            return (
                "audio",
                getattr(document, "file_name", None)
                or "Audio",
            )

        if mime.startswith("video/"):
            return (
                "video",
                getattr(document, "file_name", None)
                or "Video",
            )

    return None


def _source_message(update: Update):
    message = update.effective_message

    if not message:
        return None

    if message.reply_to_message:
        return message.reply_to_message

    return None


def _title(item: MediaItem) -> str:
    return item.title or item.kind.title()


# ============================================================
# PERMISSIONS
# ============================================================

async def _is_admin(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> bool:

    user = update.effective_user
    message = update.effective_message

    if not user or not message:
        return False

    if OWNER_ID is not None and user.id == OWNER_ID:
        return True

    # Private chats do not need admin permissions.
    if message.chat.type == "private":
        return True

    try:
        member = await context.bot.get_chat_member(
            message.chat.id,
            user.id,
        )

        return member.status in ADMIN_STATUSES

    except Exception:
        log.exception(
            "Admin check failed user=%s chat=%s",
            user.id,
            message.chat.id,
        )

        return False


async def _require_admin(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> bool:

    if await _is_admin(update, context):
        return True

    message = update.effective_message

    if message:
        await message.reply_text(
            "❌ هذا الأمر متاح للمشرفين فقط."
        )

    return False


# ============================================================
# CONTROL BUTTONS
# ============================================================

def _buttons(chat_id: int) -> InlineKeyboardMarkup:

    return InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    "⏸ Pause",
                    callback_data=f"mp:{chat_id}:pause",
                ),
                InlineKeyboardButton(
                    "▶️ Resume",
                    callback_data=f"mp:{chat_id}:resume",
                ),
            ],
            [
                InlineKeyboardButton(
                    "⏭ Skip",
                    callback_data=f"mp:{chat_id}:skip",
                ),
                InlineKeyboardButton(
                    "⏹ Stop",
                    callback_data=f"mp:{chat_id}:stop",
                ),
            ],
            [
                InlineKeyboardButton(
                    "📋 Queue",
                    callback_data=f"mp:{chat_id}:queue",
                ),
                InlineKeyboardButton(
                    "🔁 Repeat",
                    callback_data=f"mp:{chat_id}:repeat",
                ),
            ],
            [
                InlineKeyboardButton(
                    "🔴 Hide buttons",
                    callback_data=f"mp:{chat_id}:hide",
                ),
            ],
        ]
    )


# ============================================================
# QUEUE DISPLAY
# ============================================================

def _format_queue(state: PlayerState) -> str:

    lines = []

    if state.current:
        status = (
            "⏸ Paused"
            if state.paused
            else "▶️ Playing"
        )

        lines.append(
            f"🎵 {status}: {state.current.title}"
        )

    if state.queue:
        lines.append("")
        lines.append("📋 Queue:")

        for index, item in enumerate(state.queue, 1):
            lines.append(
                f"{index}. {item.title}"
            )

    if not lines:
        return "📋 Queue is empty."

    return "\n".join(lines)


# ============================================================
# MEDIA ENGINE
# ============================================================

async def _ensure_engine() -> None:

    global USER_CLIENT
    global CALLS
    global _ENGINE_READY

    if (
        _ENGINE_READY
        and USER_CLIENT is not None
        and CALLS is not None
    ):
        if (
            getattr(USER_CLIENT, "is_connected", False)
            or getattr(USER_CLIENT, "is_started", False)
        ):
            return

    async with _ENGINE_LOCK:

        if (
            _ENGINE_READY
            and USER_CLIENT is not None
            and CALLS is not None
        ):
            if (
                getattr(USER_CLIENT, "is_connected", False)
                or getattr(USER_CLIENT, "is_started", False)
            ):
                return

        if not API_ID or not API_HASH or not SESSION_STRING:
            raise RuntimeError(
                "Missing API_ID, API_HASH, or SESSION_STRING "
                "for the media player."
            )

        if PyTgCalls is None:
            raise RuntimeError(
                "PyTgCalls could not be imported. "
                "Check py-tgcalls installation."
            )

        if MediaStream is None:
            raise RuntimeError(
                "MediaStream could not be imported from PyTgCalls."
            )

        # ----------------------------------------------------
        # FFmpeg checks
        # ----------------------------------------------------

        ffmpeg = shutil.which("ffmpeg")
        ffprobe = shutil.which("ffprobe")

        log.info(
            "MEDIA ENGINE: ffmpeg=%s",
            ffmpeg or "NOT FOUND",
        )

        log.info(
            "MEDIA ENGINE: ffprobe=%s",
            ffprobe or "NOT FOUND",
        )

        if not ffmpeg:
            raise RuntimeError(
                "FFmpeg was not found in the system PATH."
            )

        if not ffprobe:
            log.warning(
                "FFprobe was not found in the system PATH. "
                "Some media formats may fail."
            )

        # ----------------------------------------------------
        # Versions
        # ----------------------------------------------------

        try:
            import importlib.metadata as metadata

            pyrogram_version = metadata.version(
                "pyrogram"
            )

            pytgcalls_version = metadata.version(
                "py-tgcalls"
            )

        except Exception:
            pyrogram_version = "unknown"
            pytgcalls_version = "unknown"

        log.info(
            "MEDIA ENGINE: pyrogram=%s pytgcalls=%s",
            pyrogram_version,
            pytgcalls_version,
        )

        # ----------------------------------------------------
        # Pyrogram
        # ----------------------------------------------------

        if USER_CLIENT is None:
            USER_CLIENT = Client(
                "fixmyenglish_player",
                api_id=API_ID,
                api_hash=API_HASH,
                session_string=SESSION_STRING,
                in_memory=True,
            )

        if not getattr(
            USER_CLIENT,
            "is_connected",
            False,
        ):

            log.info(
                "MEDIA ENGINE: starting Pyrogram user client..."
            )

            await USER_CLIENT.start()

            log.info(
                "MEDIA ENGINE: Pyrogram user client started."
            )

        # ----------------------------------------------------
        # PyTgCalls
        # ----------------------------------------------------

        if CALLS is None:

            log.info(
                "MEDIA ENGINE: creating PyTgCalls..."
            )

            CALLS = PyTgCalls(USER_CLIENT)

            log.info(
                "MEDIA ENGINE: starting PyTgCalls..."
            )

            result = CALLS.start()

            if inspect.isawaitable(result):
                await result

            log.info(
                "MEDIA ENGINE: PyTgCalls started."
            )

            _register_call_events()

        _ENGINE_READY = True


# ============================================================
# STREAM EVENTS
# ============================================================

def _register_call_events() -> None:

    global _EVENTS_REGISTERED

    if _EVENTS_REGISTERED:
        return

    if (
        CALLS is None
        or call_filters is None
        or StreamEnded is None
    ):
        raise RuntimeError(
            "PyTgCalls event API is unavailable."
        )

    @CALLS.on_update(call_filters.stream_end())
    async def _stream_end_handler(_, update):

        chat_id = getattr(
            update,
            "chat_id",
            None,
        )

        if chat_id is None:
            return

        log.info(
            "MEDIA EVENT: stream ended chat=%s",
            chat_id,
        )

        asyncio.create_task(
            _handle_stream_end(int(chat_id))
        )

    _EVENTS_REGISTERED = True


# ============================================================
# CALL CONTROL
# ============================================================

async def _safe_leave(chat_id: int) -> None:

    if CALLS is None:
        return

    try:
        result = CALLS.leave_call(chat_id)

        if inspect.isawaitable(result):
            await asyncio.wait_for(
                result,
                20,
            )

        log.info(
            "MEDIA: left voice chat=%s",
            chat_id,
        )

    except Exception as exc:
        log.warning(
            "MEDIA: leave_call failed chat=%s error=%r",
            chat_id,
            exc,
        )


async def _safe_stop_call(chat_id: int) -> None:
    await _safe_leave(chat_id)


# ============================================================
# DOWNLOAD
# ============================================================

async def _download_item(
    item: MediaItem,
) -> str:

    if USER_CLIENT is None:
        raise RuntimeError(
            "Pyrogram media client is not running."
        )

    source = await asyncio.wait_for(
        USER_CLIENT.get_messages(
            item.chat_id,
            item.message_id,
        ),
        timeout=MESSAGE_TIMEOUT,
    )

    if not source:
        raise RuntimeError(
            "The source Telegram message could not be found."
        )

    source_media = _media_from_message(source)

    if source_media is None:
        raise RuntimeError(
            "The source message no longer contains playable media."
        )

    prefix = (
        f"fixmyenglish_"
        f"{item.chat_id}_"
        f"{item.message_id}_"
    )

    path = await asyncio.wait_for(
        USER_CLIENT.download_media(
            source,
            file_name=str(
                TEMP_ROOT / prefix
            ),
        ),
        timeout=DOWNLOAD_TIMEOUT,
    )

    if not path:
        raise RuntimeError(
            "Telegram media download returned no file."
        )

    log.info(
        "MEDIA DOWNLOAD: chat=%s message=%s path=%s",
        item.chat_id,
        item.message_id,
        path,
    )

    return str(path)


async def _cleanup_path(
    path: Optional[str],
) -> None:

    if not path:
        return

    try:
        await asyncio.to_thread(
            Path(path).unlink,
            True,
        )

    except FileNotFoundError:
        pass

    except Exception:
        log.exception(
            "MEDIA: failed to delete temp file %s",
            path,
        )


# ============================================================
# NOW PLAYING
# ============================================================

async def _send_now_playing(
    chat_id: int,
    item: MediaItem,
    context: ContextTypes.DEFAULT_TYPE | None = None,
) -> None:

    bot = None

    if context is not None:
        bot = context.bot

    elif BOT_INSTANCE is not None:
        bot = BOT_INSTANCE

    if bot is None:
        log.warning(
            "MEDIA: no Telegram bot instance available "
            "for now-playing message."
        )
        return

    send_kwargs = {
        "chat_id": chat_id,
        "text": (
            "🎵 <b>Now Playing</b>\n\n"
            f"• {item.title}\n"
            f"• Type: {item.kind}\n"
            f"• Requested by: {item.requester_id}"
        ),
        "parse_mode": "HTML",
        "reply_markup": _buttons(chat_id),
    }

    # Critical for Telegram forum topics.
    # None means General/non-topic chat.
    if item.thread_id is not None:
        send_kwargs["message_thread_id"] = item.thread_id

    try:
        await bot.send_message(**send_kwargs)

    except Exception:
        log.exception(
            "MEDIA: failed to send now-playing message "
            "chat=%s thread=%s",
            chat_id,
            item.thread_id,
        )


# ============================================================
# STREAM CREATION
# ============================================================

def _build_stream(
    item: MediaItem,
    path: str,
):
    """
    Build the correct PyTgCalls stream.

    audio:
        video is explicitly ignored.

    video:
        both audio and video are streamed.
    """

    if MediaStream is None:
        raise RuntimeError(
            "PyTgCalls MediaStream is unavailable."
        )

    if item.kind == "video":

        if AudioQuality is None:
            raise RuntimeError(
                "PyTgCalls AudioQuality is unavailable."
            )

        if VideoQuality is None:
            raise RuntimeError(
                "PyTgCalls VideoQuality is unavailable."
            )

        return MediaStream(
            path,
            AudioQuality.HIGH,
            VideoQuality.HD_720p,
        )

    # Audio-only mode.
    return MediaStream(
        path,
        video_flags=MediaStream.Flags.IGNORE,
    )


# ============================================================
# START CURRENT TRACK
# ============================================================

async def _start_current(
    chat_id: int,
    context: ContextTypes.DEFAULT_TYPE | None = None,
) -> bool:

    state = _state(chat_id)

    if state.current is None:

        if not state.queue:
            return False

        state.current = state.queue.popleft()

    if state.starting:
        return False

    state.starting = True

    item = state.current

    try:

        log.info(
            "MEDIA START: chat=%s message=%s "
            "kind=%s title=%r thread=%s",
            chat_id,
            item.message_id,
            item.kind,
            item.title,
            item.thread_id,
        )

        await _ensure_engine()

        # ----------------------------------------------------
        # Download
        # ----------------------------------------------------

        if (
            item.temp_path
            and Path(item.temp_path).exists()
        ):
            path = item.temp_path

        else:

            log.info(
                "MEDIA START: downloading "
                "chat=%s message=%s",
                chat_id,
                item.message_id,
            )

            path = await _download_item(item)

            item.temp_path = path

        # ----------------------------------------------------
        # Build stream
        # ----------------------------------------------------

        stream = _build_stream(
            item,
            path,
        )

        log.info(
            "MEDIA START: calling PyTgCalls.play "
            "chat=%s path=%s kind=%s",
            chat_id,
            path,
            item.kind,
        )

        result = CALLS.play(
            chat_id,
            stream,
        )

        if inspect.isawaitable(result):
            await asyncio.wait_for(
                result,
                PLAY_TIMEOUT,
            )

        state.paused = False
        state.muted = False
        state.starting = False

        log.info(
            "MEDIA START: playback started "
            "chat=%s title=%r kind=%s",
            chat_id,
            item.title,
            item.kind,
        )

        await _send_now_playing(
            chat_id,
            item,
            context,
        )

        return True

    except asyncio.TimeoutError:

        log.error(
            "MEDIA START TIMEOUT: "
            "chat=%s message=%s",
            chat_id,
            item.message_id,
        )

        await _safe_leave(chat_id)

    except Exception as exc:

        log.exception(
            "MEDIA START FAILED: "
            "chat=%s message=%s error=%r",
            chat_id,
            item.message_id,
            exc,
        )

        await _safe_leave(chat_id)

    state.starting = False

    failed = state.current
    state.current = None

    if failed:
        await _cleanup_path(
            failed.temp_path
        )

    # Try the next queued item.
    if state.queue:
        return await _start_current(
            chat_id,
            context,
        )

    return False


# ============================================================
# STREAM END
# ============================================================

async def _handle_stream_end(
    chat_id: int,
) -> None:

    async with _lock(chat_id):

        state = _state(chat_id)

        # ----------------------------------------------------
        # Ignore delayed event caused by manual skip/stop.
        # ----------------------------------------------------

        if state.suppress_next_end:

            state.suppress_next_end = False

            log.info(
                "MEDIA END: suppressed delayed "
                "stream_end chat=%s",
                chat_id,
            )

            return

        finished = state.current

        if finished:

            log.info(
                "MEDIA END: chat=%s title=%r "
                "repeat=%s",
                chat_id,
                finished.title,
                state.repeat,
            )

        # ----------------------------------------------------
        # Clean finished file.
        # ----------------------------------------------------

        if finished:
            await _cleanup_path(
                finished.temp_path
            )

        # ----------------------------------------------------
        # Repeat ONE
        # ----------------------------------------------------

        if (
            state.repeat == "one"
            and finished is not None
        ):

            state.current = MediaItem(
                chat_id=finished.chat_id,
                message_id=finished.message_id,
                title=finished.title,
                kind=finished.kind,
                requester_id=finished.requester_id,
                thread_id=finished.thread_id,
            )

        else:

            # ------------------------------------------------
            # Repeat ALL
            # ------------------------------------------------

            if (
                state.repeat == "all"
                and finished is not None
            ):
                # Clear temp path because the previous file
                # was deleted and must be downloaded again.
                finished.temp_path = None

                state.queue.append(
                    finished
                )

            state.current = None

        state.paused = False
        state.starting = False

        # ----------------------------------------------------
        # Start next item.
        # ----------------------------------------------------

        started = await _start_current(
            chat_id,
            None,
        )

        # ----------------------------------------------------
        # IMPORTANT:
        # If nothing is left, leave the voice chat.
        # ----------------------------------------------------

        if not started:
            state.current = None
            state.starting = False

            if not state.queue:

                log.info(
                    "MEDIA END: queue finished; "
                    "leaving chat=%s",
                    chat_id,
                )

                await _safe_leave(
                    chat_id
                )


# ============================================================
# ENQUEUE
# ============================================================

async def _enqueue(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    mode: str = "auto",
) -> None:

    message = update.effective_message
    user = update.effective_user

    if not message or not user:
        return

    source = _source_message(update)
    media = _media_from_message(source)

    if source is None or media is None:

        await message.reply_text(
            "🎵 Reply to an audio or video message "
            "with <b>شغل</b> or <b>/play</b>.",
            parse_mode="HTML",
        )

        return

    detected_kind, title = media

    # --------------------------------------------------------
    # Determine requested playback mode.
    # --------------------------------------------------------

    if mode == "audio":

        # Any playable media can be forced to audio-only.
        kind = "audio"

    elif mode == "video":

        if detected_kind != "video":

            await message.reply_text(
                "❌ الأمر الخاص بالفيديو يحتاج إلى "
                "رسالة فيديو.",
            )

            return

        kind = "video"

    else:
        # AUTO:
        # audio stays audio.
        # video plays as video.
        kind = detected_kind

    state = _state(
        message.chat.id
    )

    if len(state.queue) >= MAX_QUEUE:

        await message.reply_text(
            f"❌ Queue is full. Maximum: {MAX_QUEUE} items."
        )

        return

    # The command's topic is the topic where the
    # controls should appear.
    thread_id = getattr(
        message,
        "message_thread_id",
        None,
    )

    # Fallback to the source media topic.
    if thread_id is None:
        thread_id = getattr(
            source,
            "message_thread_id",
            None,
        )

    item = MediaItem(
        chat_id=message.chat.id,
        message_id=source.message_id,
        title=title,
        kind=kind,
        requester_id=user.id,
        thread_id=thread_id,
    )

    async with _lock(
        message.chat.id
    ):

        state = _state(
            message.chat.id
        )

        # ----------------------------------------------------
        # Prevent duplicate media.
        # ----------------------------------------------------

        all_items = list(
            state.queue
        )

        if state.current:
            all_items.insert(
                0,
                state.current,
            )

        if any(
            x.message_id == item.message_id
            for x in all_items
        ):

            await message.reply_text(
                "ℹ️ This media is already in the player."
            )

            return

        # ----------------------------------------------------
        # Idle / Queue
        # ----------------------------------------------------

        was_idle = (
            state.current is None
            and not state.starting
        )

        if was_idle:
            state.current = item

        else:
            state.queue.append(
                item
            )

        position = (
            0
            if was_idle
            else len(state.queue)
        )

        # ----------------------------------------------------
        # Start immediately.
        # ----------------------------------------------------

        if was_idle:

            mode_text = (
                "🎬 Video + audio"
                if kind == "video"
                else "🎵 Audio"
            )

            await message.reply_text(
                f"▶️ Starting: "
                f"<b>{title}</b>\n"
                f"🎧 Mode: {mode_text}",
                parse_mode="HTML",
            )

            started = await _start_current(
                message.chat.id,
                context,
            )

            if not started:

                await message.reply_text(
                    "❌ Playback could not be started.\n"
                    "Check the Render logs for "
                    "MEDIA ENGINE / MEDIA DOWNLOAD / "
                    "MEDIA START."
                )

            return

        # ----------------------------------------------------
        # Added to queue.
        # ----------------------------------------------------

        await message.reply_text(
            f"➕ Added to queue: "
            f"<b>{title}</b>\n"
            f"📍 Position: {position}",
            parse_mode="HTML",
        )


# ============================================================
# PLAY COMMANDS
# ============================================================

async def play_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    await _enqueue(
        update,
        context,
        mode="auto",
    )


async def video_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    await _enqueue(
        update,
        context,
        mode="video",
    )


async def audio_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    await _enqueue(
        update,
        context,
        mode="audio",
    )


async def play_text_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    message = update.effective_message

    if not message or not message.text:
        return

    text = message.text.strip().lower()

    if text in {
        "شغل",
        "play",
    }:

        # Automatic:
        # audio -> audio
        # video -> video
        await _enqueue(
            update,
            context,
            mode="auto",
        )

    elif text in {
        "شغل صوت",
        "شغل صوتي",
        "play audio",
    }:

        await _enqueue(
            update,
            context,
            mode="audio",
        )

    elif text in {
        "شغل فيديو",
        "play video",
        "فيديو",
        "video",
    }:

        await _enqueue(
            update,
            context,
            mode="video",
        )


# ============================================================
# PAUSE
# ============================================================

async def pause_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        state = _state(chat_id)

        if state.current is None:

            await message.reply_text(
                "ℹ️ Nothing is playing."
            )

            return

        try:

            result = CALLS.pause(
                chat_id
            )

            if inspect.isawaitable(result):
                await asyncio.wait_for(
                    result,
                    20,
                )

            state.paused = True

            await message.reply_text(
                "⏸ Paused."
            )

        except Exception as exc:

            log.exception(
                "MEDIA PAUSE FAILED: %r",
                exc,
            )

            await message.reply_text(
                f"❌ Pause failed: {exc}"
            )


# ============================================================
# RESUME
# ============================================================

async def resume_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        state = _state(chat_id)

        if state.current is None:

            await message.reply_text(
                "ℹ️ Nothing is playing."
            )

            return

        try:

            result = CALLS.resume(
                chat_id
            )

            if inspect.isawaitable(result):
                await asyncio.wait_for(
                    result,
                    20,
                )

            state.paused = False

            await message.reply_text(
                "▶️ Resumed."
            )

        except Exception as exc:

            log.exception(
                "MEDIA RESUME FAILED: %r",
                exc,
            )

            await message.reply_text(
                f"❌ Resume failed: {exc}"
            )


# ============================================================
# SKIP
# ============================================================

async def skip_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        state = _state(chat_id)

        if state.current is None:

            await message.reply_text(
                "ℹ️ Nothing is playing."
            )

            return

        old = state.current

        # Prevent the delayed stream_end event
        # from treating the new track as finished.
        state.suppress_next_end = True

        await _safe_stop_call(
            chat_id
        )

        await _cleanup_path(
            old.temp_path
        )

        state.current = None
        state.paused = False
        state.starting = False

        started = await _start_current(
            chat_id,
            context,
        )

        if started:

            await message.reply_text(
                "⏭ Skipped."
            )

        else:

            state.suppress_next_end = False

            await message.reply_text(
                "⏭ Skipped. Queue is empty."
            )

            await _safe_leave(
                chat_id
            )


# ============================================================
# STOP
# ============================================================

async def stop_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        state = _state(chat_id)

        state.suppress_next_end = True

        await _safe_stop_call(
            chat_id
        )

        if state.current:

            await _cleanup_path(
                state.current.temp_path
            )

        for item in state.queue:

            await _cleanup_path(
                item.temp_path
            )

        state.queue.clear()
        state.current = None
        state.paused = False
        state.starting = False

        await message.reply_text(
            "⏹ Playback stopped and queue cleared."
        )


# ============================================================
# LEAVE
# ============================================================

async def leave_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        state = _state(chat_id)

        state.suppress_next_end = True

        await _safe_leave(
            chat_id
        )

        if state.current:

            await _cleanup_path(
                state.current.temp_path
            )

        for item in state.queue:

            await _cleanup_path(
                item.temp_path
            )

        state.queue.clear()
        state.current = None
        state.paused = False
        state.starting = False

        await message.reply_text(
            "👋 Left the voice chat and cleared the player."
        )


# ============================================================
# QUEUE
# ============================================================

async def queue_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    message = update.effective_message

    if not message:
        return

    await message.reply_text(
        _format_queue(
            _state(
                message.chat.id
            )
        )
    )


# ============================================================
# NOW
# ============================================================

async def now_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    message = update.effective_message

    if not message:
        return

    state = _state(
        message.chat.id
    )

    if not state.current:

        await message.reply_text(
            "ℹ️ Nothing is playing."
        )

        return

    status = (
        "⏸ Paused"
        if state.paused
        else "▶️ Playing"
    )

    await message.reply_text(
        f"🎵 {status}\n\n"
        f"• {state.current.title}\n"
        f"• Type: {state.current.kind}\n"
        f"• Volume: {state.volume}%\n"
        f"• Repeat: {state.repeat}\n"
        f"• Queue: {len(state.queue)}"
    )


# ============================================================
# CLEAR
# ============================================================

async def clear_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        state = _state(chat_id)

        count = len(
            state.queue
        )

        for item in state.queue:

            await _cleanup_path(
                item.temp_path
            )

        state.queue.clear()

        await message.reply_text(
            f"🧹 Cleared {count} queued item(s)."
        )


# ============================================================
# SHUFFLE
# ============================================================

async def shuffle_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        state = _state(chat_id)

        if len(state.queue) < 2:

            await message.reply_text(
                "ℹ️ Not enough items to shuffle."
            )

            return

        items = list(
            state.queue
        )

        random.shuffle(items)

        state.queue = deque(
            items
        )

        await message.reply_text(
            "🔀 Queue shuffled."
        )


# ============================================================
# REPEAT
# ============================================================

async def repeat_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    args = [
        x.lower()
        for x in (
            context.args or []
        )
    ]

    async with _lock(chat_id):

        state = _state(chat_id)

        if args and args[0] in {
            "off",
            "one",
            "all",
        }:

            state.repeat = args[0]

        else:

            state.repeat = {
                "off": "one",
                "one": "all",
                "all": "off",
            }[
                state.repeat
            ]

        await message.reply_text(
            f"🔁 Repeat: {state.repeat}"
        )


# ============================================================
# MUTE
# ============================================================

async def _set_mute(
    chat_id: int,
    muted: bool,
) -> None:

    if CALLS is None:
        raise RuntimeError(
            "Media engine is not running."
        )

    method_name = (
        "mute"
        if muted
        else "unmute"
    )

    method = getattr(
        CALLS,
        method_name,
        None,
    )

    if method is None:
        raise RuntimeError(
            f"PyTgCalls does not expose "
            f"{method_name}()."
        )

    result = method(
        chat_id
    )

    if inspect.isawaitable(result):

        await asyncio.wait_for(
            result,
            20,
        )


async def mute_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        try:

            await _set_mute(
                chat_id,
                True,
            )

            _state(
                chat_id
            ).muted = True

            await message.reply_text(
                "🔇 Muted."
            )

        except Exception as exc:

            log.exception(
                "MEDIA MUTE FAILED: %r",
                exc,
            )

            await message.reply_text(
                f"❌ Mute failed: {exc}"
            )


async def unmute_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    chat_id = message.chat.id

    async with _lock(chat_id):

        try:

            await _set_mute(
                chat_id,
                False,
            )

            _state(
                chat_id
            ).muted = False

            await message.reply_text(
                "🔊 Unmuted."
            )

        except Exception as exc:

            log.exception(
                "MEDIA UNMUTE FAILED: %r",
                exc,
            )

            await message.reply_text(
                f"❌ Unmute failed: {exc}"
            )


# ============================================================
# VOLUME
# ============================================================

async def volume_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    if not await _require_admin(
        update,
        context,
    ):
        return

    message = update.effective_message

    if not message:
        return

    if not context.args:

        await message.reply_text(
            "Usage: /volume 100"
        )

        return

    try:

        volume = int(
            context.args[0]
        )

    except ValueError:

        await message.reply_text(
            "❌ Volume must be a number from 0 to 200."
        )

        return

    volume = max(
        0,
        min(
            200,
            volume,
        ),
    )

    chat_id = message.chat.id

    async with _lock(chat_id):

        try:

            result = CALLS.change_volume_call(
                chat_id,
                volume,
            )

            if inspect.isawaitable(result):

                await asyncio.wait_for(
                    result,
                    20,
                )

            _state(
                chat_id
            ).volume = volume

            await message.reply_text(
                f"🔊 Volume: {volume}%"
            )

        except Exception as exc:

            log.exception(
                "MEDIA VOLUME FAILED: %r",
                exc,
            )

            await message.reply_text(
                f"❌ Volume failed: {exc}"
            )


# ============================================================
# BUTTON CALLBACKS
# ============================================================

async def _callback_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:

    query = update.callback_query

    if not query:
        return

    parts = (
        query.data or ""
    ).split(":")

    if (
        len(parts) != 3
        or parts[0] != "mp"
    ):
        return

    try:

        chat_id = int(
            parts[1]
        )

    except ValueError:
        return

    action = parts[2]

    if query.message is None:
        return

    # --------------------------------------------------------
    # Hide buttons
    # --------------------------------------------------------

    if action == "hide":

        try:

            await query.edit_message_reply_markup(
                reply_markup=None
            )

            await query.answer(
                "Buttons hidden."
            )

        except Exception:

            log.exception(
                "MEDIA: failed to hide buttons."
            )

        return

    # --------------------------------------------------------
    # Admin check
    # --------------------------------------------------------

    if not await _is_admin(
        update,
        context,
    ):

        await query.answer(
            "Admins only.",
            show_alert=True,
        )

        return

    # --------------------------------------------------------
    # Execute action
    # --------------------------------------------------------

    if action == "pause":

        await query.answer()
        await pause_handler(
            update,
            context,
        )

    elif action == "resume":

        await query.answer()
        await resume_handler(
            update,
            context,
        )

    elif action == "skip":

        await query.answer()
        await skip_handler(
            update,
            context,
        )

    elif action == "stop":

        await query.answer()
        await stop_handler(
            update,
            context,
        )

    elif action == "queue":

        await query.answer()
        await queue_handler(
            update,
            context,
        )

    elif action == "repeat":

        await query.answer()
        await repeat_handler(
            update,
            context,
        )


# ============================================================
# SHUTDOWN
# ============================================================

async def shutdown_media_player() -> None:

    global USER_CLIENT
    global CALLS
    global _ENGINE_READY
    global _EVENTS_REGISTERED
    global BOT_INSTANCE

    log.info(
        "MEDIA SHUTDOWN: starting cleanup..."
    )

    for chat_id in list(
        PLAYERS
    ):

        try:

            async with _lock(
                chat_id
            ):

                state = PLAYERS[
                    chat_id
                ]

                state.suppress_next_end = True

                if CALLS is not None:

                    await _safe_leave(
                        chat_id
                    )

                if state.current:

                    await _cleanup_path(
                        state.current.temp_path
                    )

                for item in state.queue:

                    await _cleanup_path(
                        item.temp_path
                    )

                state.queue.clear()
                state.current = None
                state.paused = False
                state.starting = False

        except Exception:

            log.exception(
                "MEDIA SHUTDOWN: "
                "chat cleanup failed chat=%s",
                chat_id,
            )

    PLAYERS.clear()
    CHAT_LOCKS.clear()

    if CALLS is not None:

        try:

            result = CALLS.stop()

            if inspect.isawaitable(result):

                await asyncio.wait_for(
                    result,
                    20,
                )

            log.info(
                "MEDIA SHUTDOWN: PyTgCalls stopped."
            )

        except Exception:

            log.exception(
                "MEDIA SHUTDOWN: "
                "PyTgCalls stop failed."
            )

    CALLS = None
    _EVENTS_REGISTERED = False

    if USER_CLIENT is not None:

        try:

            if (
                getattr(
                    USER_CLIENT,
                    "is_connected",
                    False,
                )
                or getattr(
                    USER_CLIENT,
                    "is_started",
                    False,
                )
            ):

                await asyncio.wait_for(
                    USER_CLIENT.stop(),
                    20,
                )

            log.info(
                "MEDIA SHUTDOWN: Pyrogram stopped."
            )

        except Exception:

            log.exception(
                "MEDIA SHUTDOWN: "
                "Pyrogram stop failed."
            )

    USER_CLIENT = None
    BOT_INSTANCE = None
    _ENGINE_READY = False

    log.info(
        "MEDIA SHUTDOWN: complete."
    )


async def _post_shutdown(
    application: Application,
) -> None:

    await shutdown_media_player()


# ============================================================
# REGISTRATION
# ============================================================

def register_media_play(
    application: Application,
) -> None:

    global BOT_INSTANCE

    BOT_INSTANCE = application.bot

    # --------------------------------------------------------
    # Slash commands
    # --------------------------------------------------------

    application.add_handler(
        CommandHandler(
            "play",
            play_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "video",
            video_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "audio",
            audio_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "pause",
            pause_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "resume",
            resume_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "skip",
            skip_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "stop",
            stop_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "leave",
            leave_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "queue",
            queue_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "now",
            now_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "clear",
            clear_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "shuffle",
            shuffle_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "repeat",
            repeat_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "mute",
            mute_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "unmute",
            unmute_handler,
        )
    )

    application.add_handler(
        CommandHandler(
            "volume",
            volume_handler,
        )
    )

    # --------------------------------------------------------
    # Buttons
    # --------------------------------------------------------

    application.add_handler(
        CallbackQueryHandler(
            _callback_handler,
            pattern=r"^mp:",
        )
    )

    # --------------------------------------------------------
    # Plain Arabic / English commands
    # --------------------------------------------------------

    application.add_handler(
        MessageHandler(
            filters.TEXT
            & filters.Regex(
                r"^(?:شغل|play)$"
            ),
            play_text_handler,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.TEXT
            & filters.Regex(
                r"^(?:شغل\s+صوت|شغل\s+صوتي|play\s+audio)$"
            ),
            play_text_handler,
        )
    )

    application.add_handler(
        MessageHandler(
            filters.TEXT
            & filters.Regex(
                r"^(?:شغل\s+فيديو|play\s+video|فيديو|video)$"
            ),
            play_text_handler,
        )
    )

    # --------------------------------------------------------
    # PTB shutdown
    # --------------------------------------------------------

    application.post_shutdown = _post_shutdown

    log.info(
        "MEDIA PLAY: handlers registered successfully."
                )
